databases:
  - name: gestionale-db
    databaseName: gestionale_db
    user: gestionale

services:
  # Backend FastAPI
  - type: web
    name: gestionale-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gestionale-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: FRONTEND_URL
        value: https://gestionale-frontend-aa3q.onrender.com
    healthCheckPath: /api/health

  # Frontend React
  - type: web
    name: gestionale-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://gestionale-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
